require "logger"
require "json/jwt"
require "uri"
require "date"
require "net/http"

require "active_support/all"

require "anyway_config"
require "dry/auto_inject"
require "dry/container"
require "dry/effects"
require "dry/initializer"
require "dry/matcher"
require "dry/monads"
require "dry/struct"
require "dry/types"
require "dry/validation"

require "dry/monads/result"
require "dry/matcher/result_matcher"

Dry::Types.load_extensions(:monads)

require_relative "keycloak-api-rails/types"
require_relative "keycloak-api-rails/config"
require_relative "keycloak-api-rails/container"
require_relative "keycloak-api-rails/import"
require_relative "keycloak-api-rails/decoded_token"
require_relative "keycloak-api-rails/http_client"
require_relative "keycloak-api-rails/authenticate"
require_relative "keycloak-api-rails/read_token"
require_relative "keycloak-api-rails/skip_authentication"
require_relative "keycloak-api-rails/token_error"
require_relative "keycloak-api-rails/helper"
require_relative "keycloak-api-rails/public_key_resolver"
require_relative "keycloak-api-rails/public_key_cached_resolver"
require_relative "keycloak-api-rails/service"
require_relative "keycloak-api-rails/session"
require_relative "keycloak-api-rails/authorize_realm"
require_relative "keycloak-api-rails/authorize_resource"
require_relative "keycloak-api-rails/middleware"
require_relative "keycloak-api-rails/railtie" if defined?(Rails)
